### ISSUE TITLE
Instant Update Callback

### ISSUE THREAD

**Issue by dottodot** [ndaidong/paypal-nvp-api#5]
Just wondering does support the Instant Update Callback API?

**Comment by ndaidong** [comment]
@dottodot  Sorry for missing your feedback. Here is the first time I heard about this API. Will try to implement it.

**Comment by ndaidong** [comment]
@dottodot we don't need to change any part of this library to support Instant Update Callback API. When you call SetExpressCheckout, just add the necessary properties to get instant callbacks from Paypal server.
